### ISSUE TITLE
helm 3 installation steps 

### ISSUE THREAD

**Issue by prasathkumarramachandran** [Vishesh30/Node-express-Postgress-helm#1]
Helm 2 installation steps seems to be outdated.. "helm install ." is not working anymore..in helm 3

For helm 3 in docker desktop . Please follow the below commands

Clone the repository from git
In the git folder / Node-express-Postgress-helm  - Execute the following command
`"helm install service-chart --generate-name"`
**Expected result** 
NAME: service-chart-1581162833
LAST DEPLOYED: Sat Feb  8 17:23:53 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

**Comment by Vishesh30** [comment]
I have enhanced the ReadMe for helm 3 as well.
